### ISSUE TITLE
Polar assets have bad geometries and bounding boxes

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/modis#89]
As originally reported https://github.com/microsoft/PlanetaryComputer/discussions/121. [@Pete Gadomski](https://dev.azure.com/planetary-computer/Planetary%20Computer%20Components/_backlogs/backlog/Team%20Element%2084/Stories/?showParents=true&workitem=3603#) did some digging to confirm the issue:

![Image](https://user-images.githubusercontent.com/58314/210104857-f47d494b-28d3-4c39-9212-18c689ae01de.png)

**Comment by pjhartzell** [comment]
Screen grab of the Item in question ([MYD10A1.A2007357.h15v16.061.2021081061440](https://planetarycomputer.microsoft.com/api/stac/v1/collections/modis-10A1-061/items/MYD10A1.A2007357.h15v16.061.2021081061440)) and the NDSI_Snow_Cover asset into QGIS. Red is the Item geometry, blue is the asset raster.

<img width="1611" alt="image" src="https://user-images.githubusercontent.com/7013017/210872384-a7bae9d3-6cc2-4163-8467-01f1ce6a5948.png">

The problem is in the XML metadata file. It contains the incorrect coordinates used to build the (incorrect) Item geometry. The source HDF file, however, contains proper bounding values.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/7013017/210872943-3410dd8b-6aa1-46f2-aece-1552c8308539.png">

@gadomski We may need to switch to using the asset data (rather than metadata) for at least the Item geometry. However, any fix should probably include the new [stactools raster footprint](https://github.com/stac-utils/stactools/blob/main/src/stactools/core/utils/raster_footprint.py) to capture the distorted wgs84 raster boundary in the Item geometry. Thoughts?
